services:
  db:
    image: postgres:17-alpine
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ~/apps/iot-hub-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

  adminer:
    image: adminer
    ports:
      - 8080:8080